---
- name: Find environment path (DT Pan-Net ALiEn)
  set_fact:
    tfvars_path: "../../envs/{{ lookup('env', 'TARGET_ENVIRONMENT') }}"
  when: ALiEn

- name: Translate Terraform tfvars to Ansible Local Facts
  tfvars_facts:
    src: "{{ tfvars_path }}/{{ tfvars_file }}"
    dest: tfvars.json
  delegate_to: localhost
  run_once: yes

- name: Create /etc/ansible/facts.d folder
  file:
    path: "{{ local_facts_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Terraform vars to the hosts
  copy:
    src: tfvars.json
    dest: "{{ local_facts_path }}/{{ local_facts_file }}"

- name: Read new Ansible facts
  setup:
  when: reload_facts