---
- name: Find environment path (DT Pan-Net ALiEn)
  set_fact:
    tfvars_path: "../../envs/{{ lookup('env', 'TARGET_ENVIRONMENT') }}"
  when: ALiEn

- name: Translate Terraform tfvars to Ansible Local Facts
  tfvars2facts:
