---
- name: Find environment path (DT Pan-Net ALiEn)
  set_fact:
    tfvars_path: "../../envs/{{ lookup('env', 'TARGET_ENVIRONMENT') }}"
  when: ALiEn

- name: Translate Terraform tfvars to Ansible Local Facts
  tfvars2facts:
    src: "{{ tfvars_path }}/{{ tfvars_file }}"
    dest: /tmp/tfvars.json
  delegate_to: localhost
  run_once: yes

- name: Copy Terraform vars to the hosts
  copy:
    src: /tmp/tfvars.json
    dest: "{{ local_facts_path }}/{{ local_facts_file }}"