---
- name: Converge
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    tfvars_path: ./tests
    reload_facts: yes
  roles:
    - role: ansible-tfvars2facts
  post_tasks:
    - name: Test to red the variables
      debug:
        msg: "{{ ansible_local['tfvars']['os_jumphost_template'] }}, \
              {{ ansible_local['tfvars']['os_app_template'] }}, \
              {{ ansible_local['tfvars']['vm_name'][1] }}, \
              {{ ansible_local['tfvars']['folder'] }}, \
              {{ ansible_local['tfvars']['vm_count'] }}, \
              {{ ansible_local['tfvars']['memory'] }}, \
              {{ ansible_local['tfvars']['vip_address_frontend'][0] }}, \
              {{ ansible_local['tfvars']['vip_ad_d_r_e_s_s_backend_x_y'] }}"